### ISSUE TITLE
VacuumEntity instead of StateVacuumEntity

### ISSUE THREAD

**Issue by michaelhenningersrb** [plakna/ha-lg-hombot#4]
Hey, I updated to the latest version of Homeassistant, and got the following error:

![image](https://github.com/plakna/ha-lg-hombot/assets/18479766/d7dffb54-67ea-43e5-9454-9624f11c7624)

The error message means that the baseclass is used wrong. It has to be `StateVacuumEntity` instead of `VacuumEntity`.

Is this planned to changed?

Thnx, for your great work @plakna ;)

**Comment by plakna** [comment]
I've already fixed this issue locally. I'll run some final tests over the weekend (or maybe tomorrow), and if everything checks out, I'll push a new version :)

**Comment by michaelhenningersrb** [comment]
Great! Thank you

**Comment by plakna** [comment]
I published a new version :)

Please be aware that due to this necessary adjustments, the status of the vacuum cleaners have been standardized according to Home Assistant's specifications. As a result, this integration now updates the statuses as follows:

- `CHARGING` -> `DOCKED`
- `BACKMOVING_INIT` -> `CLEANING`
- `WORKING` -> `CLEANING`
- `PAUSE` -> `PAUSED`
- `HOMING` -> `RETURNING`
- `DOCKING` -> `RETURNING`

Additionally, these changes also impact the services. Instead of using `vacuum.turn_on` (which seems to be deprecated by Home Assistant), please utilize `vacuum.start` (the new variant).
